#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2-0-11"
URL="http://download.simplemachines.org/index.php/smf_${VERSION}_install.tar.gz"

dl $URL /usr/local/src

