#!/bin/sh -ex

DB_NAME=simplemachines
DB_USER=simplemachines
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/simplemachines
VERSION=2.1.7

# unpack and set permissions
mkdir -p $WEBROOT
tar -zxf "$SRC/smf-$VERSION.tar.gz" --strip-components=1 -C $WEBROOT
mv $WEBROOT/other/install.php $WEBROOT/
mv $WEBROOT/other/install_2-1_mysql.sql $WEBROOT/
rm "$SRC/smf-$VERSION.tar.gz"
touch $WEBROOT/Settings.php $WEBROOT/Settings_bak.php
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/Themes
chown -R www-data:www-data $WEBROOT/Smileys
chown -R www-data:www-data $WEBROOT/avatars
chown -R www-data:www-data $WEBROOT/custom_avatar
chown -R www-data:www-data $WEBROOT/Packages
chown -R www-data:www-data $WEBROOT/attachments
chown www-data:www-data $WEBROOT/agreement.txt
chown www-data:www-data $WEBROOT/Settings.php
chown www-data:www-data $WEBROOT/Settings_bak.php
chmod 640 $WEBROOT/Settings.php
chmod 640 $WEBROOT/Settings_bak.php

# configure apache
a2dissite 000-default
a2ensite simplemachines
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# Do not expose generated database credentials in build logs.
set +x
$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'; FLUSH PRIVILEGES;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}?step=0" --data "contbutt=Continue"
$CURL "${URL}?step=2" --data "db_type=mysql&db_server=localhost&db_user=$DB_USER&db_passwd=$DB_PASS&db_name=$DB_NAME&db_prefix=&contbutt=Continue"
$CURL "${URL}?step=3" --data "mbname=TurnKey+SimpleMachines&boardurl=http%3A%2F%2F$DOMAIN&dbsession=on&utf8=on&contbutt=Continue"
$CURL "${URL}?step=4" --data "pop_done=1&contbutt=Continue"
$CURL "${URL}?step=5" --data "username=$ADMIN_NAME&password1=$ADMIN_PASS&password2=$ADMIN_PASS&email=$EMAIL&server_email=$EMAIL&password3=$DB_PASS&contbutt=Continue"

rm $WEBROOT/install*
rm -f /tmp/cookie
set -x

# stop services
service mysql stop
service apache2 stop
