#!/bin/sh -ex

DB_NAME=simplemachines
DB_USER=simplemachines
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/simplemachines

# unpack and set permissions
mkdir -p $WEBROOT
tar -zxf $SRC/smf_*_install.tar.gz -C $WEBROOT
rm $SRC/smf_*_install.tar.gz
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/Themes
chown -R www-data:www-data $WEBROOT/Smileys
chown -R www-data:www-data $WEBROOT/avatars
chown -R www-data:www-data $WEBROOT/Packages
chown -R www-data:www-data $WEBROOT/attachments
chown www-data:www-data $WEBROOT/agreement.txt
chown www-data:www-data $WEBROOT/Settings.php
chown www-data:www-data $WEBROOT/Settings_bak.php
chmod 640 $WEBROOT/Settings.php
chmod 640 $WEBROOT/Settings_bak.php

# configure apache
a2dissite 000-default
a2ensite simplemachines
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}?step=0" --data "contbutt=Continue"
$CURL "${URL}?step=2" --data "db_type=mysql&db_server=localhost&db_user=$DB_USER&db_passwd=$DB_PASS&db_name=$DB_NAME&db_prefix=&contbutt=Continue"
$CURL "${URL}?step=3" --data "mbname=TurnKey+SimpleMachines&boardurl=http%3A%2F%2F$DOMAIN&dbsession=on&utf8=on&contbutt=Continue"
$CURL "${URL}?step=4" --data "pop_done=1&contbutt=Continue"
$CURL "${URL}?step=5" --data "username=$ADMIN_NAME&password1=$ADMIN_PASS&password2=$ADMIN_PASS&email=$EMAIL&password3=$DB_PASS&contbutt=Continue"

rm $WEBROOT/install*
rm -f /tmp/cookie

# stop services
service mysql stop
service apache2 stop
